all: search MinHeap coloring

search: search.cpp 
	g++ -g -Wall -w -std=c++11 $^ -o $@

MinHeap: MinHeap.h
	g++ -g -Wall -w -std=c++11 $^ -o $@

coloring: coloring.cpp
	 g++ -g -Wall -w -std=c++11 $^ -o $@