all: msort

cave: cave.cpp 
	g++ -g -Wall -w -std=c++11 $^ -o $@

fatalist: fatalist.cpp
	g++ -g -Wall -w -std=c++11 $^ -o $@

functor: functor.cpp functor.h
	g++ -g -Wall -w -std=c++11 $^ -o $@

msort: msort.h
	g++ -g -Wall -w -std=c++11 $^ -o $@

